name: cd

on:
  push:
    branches: [main]

jobs:        
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Build
        run: scripts/buildprod.sh

      - name: Run migrations
        run: scripts/migrateup.sh
